### ISSUE TITLE
Global user/password configuration

### ISSUE THREAD

**Issue by femueller** [dokku/dokku-http-auth#11]
It would be nice to have a global `htpasswd` configuration, which can be enabled for all Dokku apps.
This would help avoiding repetitive user/password creation.

Similar to:
```
dokku config:show [--merged] (<app>|--global)
dokku config:set [--encoded] [--no-restart] (<app>|--global) KEY1=VALUE1 [KEY2=VALUE2 ...]
```

**Comment by josegonzalez** [comment]
This might be useful, but I am not interested in adding more global config like that (or via this plugin directly). Global config is actually fairly annoying to deal with.

Closing this for now as I don't think I'll be working on this, but if someone wants to make an MR that adds such functionality to this plugin (without using app env vars), I'd be willing to merge.
