### ISSUE TITLE
Feature request: Whitelist IP adresses, otherwise block all connections with no http auth

### ISSUE THREAD

**Issue by gleniat** [dokku/dokku-http-auth#16]
Hi!

I'd like to simply block all connections + whitelist IP addresses that can access the app without auth.
Is it possible to do it with this plugin?

Thank you

**Comment by josegonzalez** [comment]
Yes, that's odd possible and documented in the readme.

**Comment by gleniat** [comment]
Hi josegonzalez,

Maybe I wasn’t clear enough. So let me try to clarify.

I'd like to achieve this: add XXX.XXX.XXX.XXX and YYY.YYY.YYY.YYY IPs to a whitelist. Don't add any auth users.

- If the site is visited from XXX.XXX.XXX.XXX or YYY.YYY.YYY.YYY, display the site normally
- If the site is visited from another IP address, display an HTTP 404 error

I'd like to hide the site from the public completely.
Is this currently achievable with this plugin somehow?

Thank you!

**Comment by josegonzalez** [comment]
Is that possible at all with nginx auth?

**Comment by josegonzalez** [comment]
Yeah i think you can just do:

```shell
dokku http-auth:enable node-js-app
dokku http-auth:add-allowed-ip node-js-app 127.0.0.1
```

Have you tried the above?

**Comment by gleniat** [comment]
Yes I've tried that, it still shows the http auth dialog for other IP addresses. I'd like to show 404, 403, or 401 right away.

Basically I'd like to set

```
server {
  ...
  allow 222.222.222.222;
  deny all;
 }
```

somehow.

**Comment by josegonzalez** [comment]
This plugin doesn't do that. It probably can, if we gate the `htpasswd` bit of the template behind checking if there are any users.

**Comment by gleniat** [comment]
That would be nice.

I've just discovered that I can create a file `/home/dokku/myapp/nginx.conf.d/restrict-ips.conf`, chown it to `dokku:dokku` and insert these two lines in it:

```
allow 222.222.222.222;
deny all;
```

and it seems it does what I needed. I hope it is a clean solution.

Thank you
