### ISSUE TITLE
HTTP auth is disabled after rebuild a app

### ISSUE THREAD

**Issue by maiconsanson** [dokku/dokku-http-auth#4]
After upgrade Dokku from 0.7.0 to 0.7.1 (according basic instructions from docs) and rebuild all my apps the plugin has disabled completely. I had to create all usernames and passwords for all apps again.

Is this expected?

**Comment by shovon** [comment]
I get a similar issue; simply pushing changes disables basic-auth, and I am required to re-enable it.

**Comment by shovon** [comment]
NEVER MIND! I'm so stupid.

On Chrome, the session is stored, which doesn't require me to enter the username and password a second time, hence the initial confusion.

Disregard my comment.

**Comment by shovon** [comment]
@Mehonoshin I can't. I'm not the one who created this issue.

**Comment by Mehonoshin** [comment]
@shovon sorry for disturbing then :)
