### ISSUE TITLE
Add information about bcrypt required on the server

### ISSUE THREAD

**Issue by timonweb** [dokku/dokku-http-auth#8]
If the server (Ubuntu LTS 16.04 in my case) doesn't have bcrypt installed, user will get a 500 error after enabling http_auth for an app.

I suggest adding a note about bcrypt requirement to the README. On Ubuntu bcrypt can be installed as easy as:

`sudo apt-get install bcrypt`

**Comment by justintemps** [comment]
I did not have to do this and it still worked fine.

**Comment by josegonzalez** [comment]
What error do you get in this case?

**Comment by josegonzalez** [comment]
Closing as I'm not able to replicate this.
